def giv_submission_form(driver, by):
    checkout_button = driver.find_element(by.ID, "checkout")
    checkout_button.click()
    first_name_input = driver.find_element(by.ID, "first-name")
    first_name_input.send_keys("standard_user")
    last_name_input = driver.find_element(by.ID, "last-name")
    last_name_input.send_keys("standard_user_last")
    postal_code = driver.find_element(by.ID, "postal-code")
    postal_code.send_keys("123456")
    continue_button = driver.find_element(by.ID, "continue")
    continue_button.click()
    print("\nФорма успешно заполнена и отправлена...")